"""Controlled fractional attachments; no synthetic territorial inputs."""
from copy import deepcopy
from hashlib import sha256

import pytest

from src.phase2_rt031_occurrence_binding_v3 import NODE, SEGMENT, bind_occurrences, concatenate_available


def fixture():
    corridor = dict(corridor_id="c", pair_id="ab", graph_epoch_id="epoch",
                    path_geometry_sha256="geom", path_edge_ids="a", path_node_ids="A;B",
                    elementary_for_structural_reduction="True", source_stop_place_id="A", target_stop_place_id="B")
    pattern = dict(realization_id="r", corridor_id="c", pair_id="ab", graph_epoch_id="epoch",
                   path_geometry_sha256="geom", path_edge_ids_sha256=sha256(b"a").hexdigest(),
                   structural_link_id="L", direction="A_TO_B", source_endpoint_stop_id="A",
                   target_endpoint_stop_id="B", passenger_stop_count="3", ordered_passenger_stop_ids="A;S;B")
    stops = [dict(stop_place_id=s, graph_node_id=s, graph_epoch_id="epoch", service_class="CONVENTIONAL_TPL",
                  automatic_materialization_eligible="True") for s in ("A", "S", "B")]
    occurrences = []
    for seq, (s, pos) in enumerate((("A", "0"), ("S", "0.25"), ("B", "1")), 1):
        occurrences.append({**pattern, "stop_place_id": s, "stop_sequence": str(seq), "ordinal_position": str(seq),
                            "path_position": pos, "distance_from_path_start_m": str(float(pos) * 100),
                            "evidence_type": SEGMENT if s == "S" else NODE,
                            "path_node_id": "" if s == "S" else s, "path_edge_id": "a" if s == "S" else "",
                            "certified_attachment_node_id": s, "route_proximity_buffer_m": "0",
                            "global_nearest_physical_segment_id": "RT030_SEG_" + sha256(b"A|B").hexdigest()[:20].upper()})
    return dict(patterns=[pattern], occurrences=occurrences, corridors=[corridor],
                edges=[dict(edge_id="a", u_node_id="A", v_node_id="B", length_m="100")], stops=stops, epoch="epoch")


def test_fractional_position_is_preserved_without_served_claim():
    bound = bind_occurrences(**fixture())
    visit = bound["r"]["payload"]["visits"][1]
    assert visit["binding"]["fraction"] == "0.25"
    assert visit["binding"]["edge_id"] == "a"
    assert visit["binding"]["node_id"] is None
    assert visit["pickup"] is visit["dropoff"] is visit["public_service"] is None
    assert visit["source_occurrence"]["path_position"] == "0.25"


@pytest.mark.parametrize("mutation", ["position", "distance", "carrier", "stop", "epoch", "direction", "sequence", "buffer", "physical", "ordinal", "unknown"])
def test_bad_binding_rejected(mutation):
    f = fixture()
    row = f["occurrences"][1]
    if mutation == "position": row["path_position"] = "NaN"
    if mutation == "distance": row["distance_from_path_start_m"] = "60"
    if mutation == "carrier": row["path_edge_id"] = "different-carrier"
    if mutation == "stop": f["stops"][1]["service_class"] = "SPECIAL_SERVICE"
    if mutation == "epoch": row["graph_epoch_id"] = "other"
    if mutation == "direction": row["direction"] = "B_TO_A"
    if mutation == "sequence": row["stop_sequence"] = "1"
    if mutation == "buffer": row["route_proximity_buffer_m"] = "10"
    if mutation == "physical": row["global_nearest_physical_segment_id"] = "wrong"
    if mutation == "ordinal": row["ordinal_position"] = "1"
    if mutation == "unknown": row["evidence_type"] = "NEAREST_NODE_GUESS"
    with pytest.raises(ValueError): bind_occurrences(**f)


def test_input_order_invariant():
    f = fixture()
    r = bind_occurrences(**f)
    f["occurrences"].reverse(); f["stops"].reverse()
    assert r == bind_occurrences(**f)


def test_repeated_carrier_preserves_fractional_revisits_and_unknown_legality():
    f = fixture()
    bound = bind_occurrences(**f)
    # Separately supplied reverse evidence; NEVER generated by production binder.
    reverse = deepcopy(bound["r"])
    p = reverse["payload"]
    p["carrier"][0]["source_edge"].update(edge_id="reverse", u_node_id="B", v_node_id="A")
    p["visits"] = []
    bound["reverse"] = reverse
    result = concatenate_available(bound, ["r", "reverse", "r"])["payload"]
    fractional = [v["composed_position"] for v in result["visits"] if v["source_visit"]["source_occurrence"]["stop_place_id"] == "S"]
    assert fractional == ["0.25", "2.25"]
    assert len(result["carrier"]) == 3
    assert result["turn_composition_status"] == "UNKNOWN_EVIDENCE"
    assert result["passenger_guarantees"] is None


def test_disconnected_composition_rejected():
    b = bind_occurrences(**fixture())
    with pytest.raises(ValueError, match="disconnected"):
        concatenate_available(b, ["r", "r"])
