from __future__ import annotations

import csv
import json
from pathlib import Path

import pytest

from scripts.phase2_run_structural_search import (
    load_anchor_universe,
    load_reduced_path_matrix,
    write_catalog,
    write_validation,
)
from src.phase2_optimizer_core import generate_structural_scenarios


def write_csv(path: Path, fieldnames: list[str], rows: list[dict]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def test_anchor_contract_rejects_invalidated_and_placeholder(tmp_path: Path) -> None:
    path = tmp_path / "anchors.csv"
    write_csv(
        path,
        ["anchor_id", "evidence_status", "enabled"],
        [
            {"anchor_id": "H", "evidence_status": "FACT", "enabled": "true"},
            {"anchor_id": "X", "evidence_status": "INVALIDATED", "enabled": "true"},
        ],
    )
    with pytest.raises(ValueError, match="forbidden evidence state"):
        load_anchor_universe(path)


def test_disabled_anchor_is_not_loaded(tmp_path: Path) -> None:
    path = tmp_path / "anchors.csv"
    write_csv(
        path,
        ["anchor_id", "evidence_status", "enabled"],
        [
            {"anchor_id": "H", "evidence_status": "FACT", "enabled": "true"},
            {"anchor_id": "A", "evidence_status": "DERIVED", "enabled": "false"},
        ],
    )
    assert load_anchor_universe(path) == ["H"]


def test_path_contract_is_directed_and_requires_uncertainty(tmp_path: Path) -> None:
    path = tmp_path / "matrix.csv"
    write_csv(
        path,
        ["origin", "destination", "distance_km", "runtime_min", "uncertainty"],
        [
            {"origin": "H", "destination": "A", "distance_km": 1.2, "runtime_min": 4, "uncertainty": "RESOLVED"},
            {"origin": "A", "destination": "H", "distance_km": 1.5, "runtime_min": 5, "uncertainty": "QUANTIFIED"},
        ],
    )
    matrix = load_reduced_path_matrix(path)
    assert matrix.route_metrics(("H", "A", "H")) == (2.7, 9.0, "QUANTIFIED")


def test_catalog_and_validation_are_reproducible(tmp_path: Path) -> None:
    anchors_path = tmp_path / "anchors.csv"
    matrix_path = tmp_path / "matrix.csv"
    out1 = tmp_path / "catalog1.csv"
    out2 = tmp_path / "catalog2.csv"
    val1 = tmp_path / "validation1.json"
    val2 = tmp_path / "validation2.json"

    write_csv(
        anchors_path,
        ["anchor_id", "evidence_status", "enabled"],
        [
            {"anchor_id": "H", "evidence_status": "FACT", "enabled": "true"},
            {"anchor_id": "A", "evidence_status": "DERIVED", "enabled": "true"},
            {"anchor_id": "B", "evidence_status": "PROPOSED_STOP/FIELD_CHECK_PENDING", "enabled": "true"},
            {"anchor_id": "C", "evidence_status": "ASSUMPTION", "enabled": "true"},
        ],
    )
    rows = []
    ids = ["H", "A", "B", "C"]
    for i, origin in enumerate(ids):
        for j, destination in enumerate(ids):
            if origin == destination:
                continue
            rows.append(
                {
                    "origin": origin,
                    "destination": destination,
                    "distance_km": 1 + abs(i - j) / 10,
                    "runtime_min": 3 + abs(i - j),
                    "uncertainty": "RESOLVED",
                }
            )
    write_csv(
        matrix_path,
        ["origin", "destination", "distance_km", "runtime_min", "uncertainty"],
        rows,
    )

    anchors = load_anchor_universe(anchors_path)
    matrix = load_reduced_path_matrix(matrix_path)
    first = generate_structural_scenarios(hub="H", anchors=anchors, matrix=matrix, max_scenarios=1000)
    second = generate_structural_scenarios(hub="H", anchors=anchors, matrix=matrix, max_scenarios=1000)
    write_catalog(out1, first)
    write_catalog(out2, second)
    assert out1.read_bytes() == out2.read_bytes()

    write_validation(
        val1,
        hub="H",
        anchor_path=anchors_path,
        matrix_path=matrix_path,
        output_path=out1,
        anchors=anchors,
        scenarios=first,
        max_scenarios=1000,
        max_loop_intermediate_anchors=4,
    )
    write_validation(
        val2,
        hub="H",
        anchor_path=anchors_path,
        matrix_path=matrix_path,
        output_path=out2,
        anchors=anchors,
        scenarios=second,
        max_scenarios=1000,
        max_loop_intermediate_anchors=4,
    )
    meta1 = json.loads(val1.read_text(encoding="utf-8"))
    meta2 = json.loads(val2.read_text(encoding="utf-8"))
    # Output paths differ, but the generated bytes and core provenance do not.
    assert meta1["scenario_catalog_sha256"] == meta2["scenario_catalog_sha256"]
    assert meta1["family_counts"] == meta2["family_counts"]
    assert meta1["uses_random_generation"] is False
    assert meta1["uses_live_osm"] is False
    assert meta1["uses_legacy_candidate_routes"] is False
